### ISSUE TITLE
Delete by id attaches fake entity to context

### ISSUE THREAD

**Issue by MichalTichy** [riganti/infrastructure#16]
When using method Delete(TKey Id) than the created fake entity is attached to the context.
This causes issues when Get method is used (e.q. in DeleteCore method) to acquire real entity because the fake entity is returned.

```
        public virtual void Delete(TKey id)
        {
            var fake = new TEntity() { Id = id };
            Context.Set<TEntity>().Attach(fake);
            Delete(fake);
        }
```

**Comment by luboshl** [comment]
Maybe it will be necessary to use `Context.Set<TEntity>().Find(...)` first to get the real entity from the database first. Or from the context, if it is already there.
