### ISSUE TITLE
Separate migrations

### ISSUE THREAD

**Issue by PetrSvirak** [riganti/infrastructure#5]
It does not make sense for the migrations to be part of the production code. When moving to production, one will typically create a set of SQL scripts that will be eventually customized and under the direct control of the upgrader.

Also, all migrations from all contexts should be at one place (including identity)

**Comment by tomasherceg** [comment]
There are no migrations in this repository at all. Are you sure this issue belongs to this repository? 
From the diction of the issues it seems to me that you are a teacher who does a review to some school project. If someone claimed this repository is his school work, he lies.

Also, migrations can be done using many different ways. However, using EF Code First Migrations is not a problem - noone says that you have to use them in the production environment. You can simply generate SQL scripts and run them manually, the migrations support this scenario.
Also, there is nothing wrong if migrations are part of production code - it depends on the scenario and processes of deployment.

**Comment by PetrSvirak** [comment]
Nope, I'm terribly sorry. All the issues belong to a completely different project. I just happen to left a wrong tab opened and started creating issues from there. Again, I'm really sorry. Feel free to delete all the issues.

I'm aware of the scenario you mention. Yet in this particular case, we target on options like automated deployment to various environments, including different test ones and further maintainability of big(ger) projects. I believe that in this case, more strict separation of concerns provides more versatile approaches.

**Comment by tomasherceg** [comment]
No problem. :-)
