### ISSUE TITLE
IFilteredQuery<TQueryableResult, TResult, TFilter> missing

### ISSUE THREAD

**Issue by LadislavBohm** [riganti/infrastructure#54]
Hi, is there any reason why interface like is missing?

```
public interface IFilteredQuery<TQueryableResult, TResult, TFilter> : IQuery<TQueryableResult, TResult> {
    TFilter Filter { get; set; }
}
```

I would like to be able inject query into my service using this interface for example like this:
```
Func<IFilteredQuery<User, UserDTO, UserFilter>> queryFactory
```
My use-case is that I would like to able to apply Expression<Func<TEntity, TKey>>>  style of sorting that is only available on IQuery<TQueryableResult, TResult> and filter it at the same time. I can implement both interfaces but I would like to be able to inject it within one common interface.

I can submit PR if it's appropriate.

**Comment by tomasherceg** [comment]
Please send a PR - if we have `IQuery<QueryableResult, TResult>` already, there is no need to have the `IFilteredQuery` too.
